# Generated by Django 2.2.5 on 2019-11-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=20)),
                ('animal_variety', models.CharField(max_length=20)),
                ('animal_sex', models.CharField(max_length=10)),
                ('animal_old', models.CharField(max_length=10)),
                ('animal_size', models.CharField(max_length=20)),
                ('animal_color', models.CharField(max_length=10)),
                ('animal_from', models.CharField(max_length=50)),
                ('animal_health', models.CharField(max_length=50)),
                ('animal_remark', models.TextField(max_length=10)),
                ('animal_image', models.ImageField(default='default_img.png', upload_to='images/')),
                ('pub_data', models.DateTimeField()),
                ('animal_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
